name: Dockerfile & Image Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-folders:
    runs-on: ubuntu-latest

    outputs:
      folders: ${{ steps.get_folders.outputs.folders }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Get list of folders with Dockerfiles
      - name: Get list of folders with Dockerfiles
        id: get_folders
        run: |
          # Find all directories containing a Dockerfile
          folders=$(find src -type f -name "Dockerfile" -exec dirname {} \;)
          
          # Output the list of folders for use in the next job
          echo "::set-output name=folders::$(echo $folders | tr '\n' ',')"

  scan:
    needs: get-folders
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-folders.outputs.folders) }}
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      # Step 3: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.0/trivy_0.59.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.59.0_Linux-64bit.deb

      # Step 4: Scan Dockerfile for each folder with Trivy (Misconfiguration scan)
      - name: Scan Dockerfile with Trivy (misconfig)
        run: trivy config --severity HIGH,CRITICAL ${{ matrix.folder }}/Dockerfile

      # Step 5: Build Docker image for each folder
      - name: Build Docker image
        run: |
          docker build -t my-app-image-${{ matrix.folder }} ${{ matrix.folder }}

      # Step 6: Scan the built Docker image with Trivy (Vulnerability scan)
      - name: Scan Docker image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL my-app-image-${{ matrix.folder }}
