name: Dockerfile & Image Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-folders:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.get_folders.outputs.folders }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of folders with Dockerfiles
        id: get_folders
        run: |
          # Find all directories containing a Dockerfile
          folders=$(find src -type f -name "Dockerfile" -exec dirname {} \;)

          # Format the list as a JSON array and output it
          folder_array=$(echo "$folders" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "::set-output name=folders::$folder_array"

  install-tools:
    runs-on: ubuntu-latest
    needs: get-folders
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.0/trivy_0.59.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.59.0_Linux-64bit.deb

  scan-dockerfile:
    runs-on: ubuntu-latest
    needs: install-tools
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-folders.outputs.folders) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan Dockerfile with Trivy (misconfig)
        run: trivy config --severity HIGH,CRITICAL ${{ matrix.folder }}/Dockerfile

  build-and-scan-image:
    runs-on: ubuntu-latest
    needs: scan-dockerfile
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-folders.outputs.folders) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-app-image-${{ matrix.folder }} ${{ matrix.folder }}

      - name: Scan Docker image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL my-app-image-${{ matrix.folder }}
