name: Dockerfile & Image Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to get all folders containing Dockerfiles
  get-folders:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.get_folders.outputs.folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of folders with Dockerfiles
        id: get_folders
        run: |
          # Find all directories containing Dockerfiles
          folders=$(find src -type f -name "Dockerfile" -exec dirname {} \;)
          
          # Debugging: output the raw folders
          echo "Found folders: $folders"
          
          # Format the list as a JSON array and output it
          folder_array=$(echo "$folders" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          # Debugging: output the formatted JSON array
          echo "Formatted folders as JSON: $folder_array"
          
          # Set the output for the next job
          echo "::set-output name=folders::$folder_array"

  # Job to install necessary tools like Docker Buildx and Trivy
  install-tools:
    runs-on: ubuntu-latest
    needs: get-folders
    if: ${{ always() }}  # Ensure it runs regardless of the folders found
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.0/trivy_0.59.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.59.0_Linux-64bit.deb

  # Job to scan Dockerfiles for misconfigurations (Trivy config scan)
  scan-dockerfile:
    runs-on: ubuntu-latest
    needs: install-tools
    if: ${{ needs.get-folders.outputs.folders != '[]' }}  # Only run if folders are found
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-folders.outputs.folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan Dockerfile with Trivy (misconfig)
        run: |
          trivy config --severity HIGH,CRITICAL ${{ matrix.folder }}/Dockerfile

  # Job to build Docker images for each folder
  build-image:
    runs-on: ubuntu-latest
    needs: scan-dockerfile
    if: ${{ needs.get-folders.outputs.folders != '[]' }}  # Only run if folders are found
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-folders.outputs.folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-app-image-${{ matrix.folder }} ${{ matrix.folder }}

  # Job to scan the built Docker image for vulnerabilities (Trivy image scan)
  scan-image:
    runs-on: ubuntu-latest
    needs: build-image
    if: ${{ needs.get-folders.outputs.folders != '[]' }}  # Only run if folders are found
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-folders.outputs.folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan Docker image with Trivy (vuln scan)
        run: |
          trivy image --severity HIGH,CRITICAL my-app-image-${{ matrix.folder }}
